source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PinchableLabel_Example', :exclusive => true do
  pod 'PinchableLabel', :path => '../'
end

target 'PinchableLabel_Tests', :exclusive => true do
  pod 'PinchableLabel', :path => '../'

  
end
